### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by LemonjamesD** [LemonjamesD/Whiteboard#10]
Implement tests
```toml
[[test]]
name = "test"
srcdir = "tests/test"
includedir = "tests/test"
```
