### ISSUE TITLE
Add options for custom linker and compiler.

### ISSUE THREAD

**Issue by LemonjamesD** [LemonjamesD/Whiteboard#5]
Add options for custom linker and compiler in the stages that will be implemented from #4.
```toml
[[bin]]
default = true
name = "Test"
compiler = "gcc"
linker = "gcc"
```
