### ISSUE TITLE
Add custom linker args and custom compiler args.

### ISSUE THREAD

**Issue by LemonjamesD** [LemonjamesD/Whiteboard#8]
Add the ability to do something like this
```toml
[[bin]]
default = true
name = "Test"
cargs = "-O2 -Wall -Wextra" # This should also be the default value if not provided
largs = "-B gcc" # This should also be the default value if not provided
```
