### ISSUE TITLE
Custom stages

### ISSUE THREAD

**Issue by LemonjamesD** [LemonjamesD/Whiteboard#9]
Something like this
```toml
[[bin]]
default = true
name = "test"
build_stage = { "foo": ["bar"], "baz": ["faz"] } # This will run stage foo then stage baz 
```
